// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BatchMainR
Rcpp::List BatchMainR(std::string dirpath, Rcpp::S4 ParMaster);
RcppExport SEXP _RangeShiftR_BatchMainR(SEXP dirpathSEXP, SEXP ParMasterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type dirpath(dirpathSEXP);
    Rcpp::traits::input_parameter< Rcpp::S4 >::type ParMaster(ParMasterSEXP);
    rcpp_result_gen = Rcpp::wrap(BatchMainR(dirpath, ParMaster));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RangeShiftR_BatchMainR", (DL_FUNC) &_RangeShiftR_BatchMainR, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RangeShiftR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
